### ISSUE TITLE
Allow configuring which browsers must be downloaded

### ISSUE THREAD

**Issue by Xotabu4** [Xotabu4/selenoid-github-action#2]
- Should download only latest chrome by default

**Comment by romsper** [comment]
This is how you can do that: 
`./cm selenoid start --browsers "chrome:88.0" --force`

**Comment by Xotabu4** [comment]
@romsper published v2 version with this feature, can you please test?

**Comment by romsper** [comment]
@Xotabu4 looks like it works well! ;) 
Thanks!
